---

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
    - mariadb-server
    - mysql
    - MySQL-python
- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0755

- name: Create MariaDB PID directory
  file: path=/var/run/mysqld state=directory owner=mysql group=mysql mode=0755

- name: Create mysql configure file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Start mariadb
  service: name=mariadb state=started enabled=yes
  when: ansible_distribution_major_version == "7"

- name: Start mariadb
  service: name=mysql state=started enabled=yes
  when: ansible_distribution_major_version == "6"

- name: Create Database
  mysql_db: name={{ dbname }} state=present

- name: Create DB user
  mysql_user: name={{ dbuser }} password={{ dbuserpass }} priv=*.*:ALL host={{ item }} state=present
  with_items:
    - '%'
    - 'localhost'
