---
- name: Copy Centos6&&Crntos7 EPEL       
  copy: src={{ item }} dest=/opt/
  with_items:
   - epel-release-6-8.noarch.rpm
   - remi-release-6.rpm
   - epel-release-latest-7.noarch.rpm

- name: Install ELEP for Centos6
  yum: name=/opt/{{ item }} state=installed
  with_items:
   - epel-release-6-8.noarch.rpm
   - remi-release-6.rpm
  when: ansible_distribution_major_version == "6"

- name: Install ELEP for Centos6
  yum: name=/opt/epel-release-latest-7.noarch.rpm state=installed
  when: ansible_distribution_major_version == "7"

