---
- name: Install kubernetes-node and flannel
  yum: name={{ item }} state=latest 
  with_items:
    - flannel
    - kubernetes-node
- name: Copy config file for kubernetes
  template: src={{ item }} dest=/etc/kubernetes/
  with_items:
    - config
    - kubelet
- name: Start kubelet kube_proxy docker
  service: name={{ item }} state=started enabled=yes
  with_items:
    - kubelet
    - kube-proxy
    - docker
- name: Copy config file for flannel
  template: src=flanneld dest=/etc/sysconfig/
- name: Restart docker AND flannel
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - docker
    - flanneld
